### DISCUSSION TITLE
when using awswrangler.redshift.connect_temp, does redshift cluster need to be publicly accessible?

### DISCUSSION THREAD

**Discussion by yubiao** [aws/aws-sdk-pandas#1482] [Q&A] [answered]
I run `awswrangler.redshift.connect_temp` on a lambda in the same AWS account as the Redshift cluster. When Redshift cluster is not set to public, I get connection timeout error when running `connect_temp`. If I set cluster to be public, connection is fine.

Does Redshift cluster have to be public in order for `connect_temp` to work?

The IAM role for my lambda has the following policy:
```
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'redshift:GetClusterCredentials'
              - 'redshift:CreateClusterUser'
              - 'redshift:DescribeClusters'
            Resource:
              - !Sub 'arn:aws:redshift:${AWS::Region}:${AWS::AccountId}:cluster:${RedshiftClusterIdentifier}'
              - !Sub 'arn:aws:redshift:${AWS::Region}:${AWS::AccountId}:dbname:${RedshiftClusterIdentifier}/${RedshiftDatabase}'
              - !Sub 'arn:aws:redshift:${AWS::Region}:${AWS::AccountId}:dbuser:${RedshiftClusterIdentifier}/${DataAppRedshiftUser}'
```
